name: Publish Docker Image

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build the Docker image
        run: |
          IMAGE_TAG=${{ github.ref_name }}
          docker build -t docker.io/${{ secrets.DOCKER_USERNAME }}/mars-rover-photos:${IMAGE_TAG} .
          docker tag docker.io/${{ secrets.DOCKER_USERNAME }}/mars-rover-photos:${IMAGE_TAG} docker.io/${{ secrets.DOCKER_USERNAME }}/mars-rover-photos:latest

      - name: Push the Docker image
        run: |
          IMAGE_TAG=${{ github.ref_name }}
          docker push docker.io/${{ secrets.DOCKER_USERNAME }}/mars-rover-photos:${IMAGE_TAG}
          docker push docker.io/${{ secrets.DOCKER_USERNAME }}/mars-rover-photos:latest
